---
title: "Ch5"
format: html
editor: visual
engine: knitr
---

In this notebook, you will find my solutions to some exercises from Chapter 5 of *Statistical Rethinking* and the assigned exercises from [this](https://github.com/bjbarrett/stat_rethinking_2025/tree/main) course.

# Chapter 5

## Book Exercises

------------------------------------------------------------------------

### Exercise 5M4

Data preparation. Standardize LDS members per 100 000 population. Merging with `WaffleDivorce` data.

```{r}
library(dplyr)
library(rethinking)

# upload data fro csv
lds <- read.csv("../data/lds.csv") %>%
  mutate(lds_prop = members / population,
         lds_per_capita = lds_prop * 100000)

data("WaffleDivorce")
lds_divorce <- WaffleDivorce %>%
  as_tibble() %>%
  select(Location, Divorce, Marriage, MedianAgeMarriage) %>%
  left_join(select(lds, state, lds_per_capita),
            by = c("Location" = "state")) %>%
  mutate(lds_per_capita = log(lds_per_capita)) %>%
  mutate(across(where(is.numeric), standardize)) %>% 
  filter(!is.na(lds_per_capita))

lds_divorce
```

Let's create the model

```{r}
m <- quap(
  alist(
    Divorce ~ dnorm(mu, sigma),
    mu <- a + bM * Marriage + bA * MedianAgeMarriage + bL * lds_per_capita,
    a ~ dnorm(0,0.2),
    c(bM, bA, bL) ~ dnorm(0,0.5),
    sigma ~ dexp(1)
  ), data=lds_divorce)

print(precis(m))
```

```{r}
plot(precis(m))
```

### Exercise 5H1

Let's use `dagitty`

```{r}
library(dagitty)

mad <- dagitty("dag{M->A->D}")
impliedConditionalIndependencies(mad)
```

### Exercise 5H2

```{r}

m5H2 <- quap(
  alist(
    # A -> D
    Divorce ~ dnorm( muD , sigmaD ),
    muD <- aD + bAD*MedianAgeMarriage,
    # M -> A
    MedianAgeMarriage ~ dnorm( muA , sigmaA ),
    muA <- aA + bMA*Marriage,
    # priors
    c(aD,aA) ~ dnorm(0,0.2),
    c(bAD,bMA) ~ dnorm(0,0.5),
    c(sigmaD,sigmaA) ~ dexp(1)
  ) , data=lds_divorce )
precis(m5H2)
```

```{r}
M_seq <- seq( from=-3 , to=3 , length.out=30 )
sim_dat <- data.frame( Marriage=M_seq )
s <- sim( m5H2 , data=sim_dat , vars=c("MedianAgeMarriage","Divorce") )
plot( sim_dat$Marriage , colMeans(s$MedianAgeMarriage) , ylim=c(-2,2) , type="l" ,
xlab="manipulated M" , ylab="counterfactual A" )
shade( apply(s$MedianAgeMarriage,2,PI) , sim_dat$Marriage )
mtext( "Counterfactual M -> A" )
```

```{r}
plot( sim_dat$Marriage , colMeans(s$D) , ylim=c(-2,2) , type="l" ,
xlab="manipulated M" , ylab="counterfactual D" )
shade( apply(s$Divorce,2,PI) , sim_dat$Marriage )
mtext( "Counterfactual M -> A -> D" )
```
